// Package docs Tung Tung Money API.
//
// Generated by swag init. Run `swag init -g cmd/server/main.go` to regenerate.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Tung Tung Money API",
        "description": "A money management API built with Go, Echo, and MongoDB",
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tung Tung Money API",
	Description:      "A money management API built with Go, Echo, and MongoDB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
